services:
  frontend-server:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - PORT=3000
      - HOST=0.0.0.0
    ports:
      - "3000:3000"
    networks:
      - web

  backend-server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - web

  proxy:
    image: nginx:stable-alpine
    depends_on:
      - frontend-server
      - backend-server
    ports:
      - "80:80"
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - web

networks:
  web:
    driver: bridge